"""
Execution wrapper template for generated Playwright tests.

This template provides the execution environment for Playwright tests
generated by the PlannerAgent. It handles:
- Browser initialization
- Screenshot capture (success and error)
- Exception handling
- Result JSON output

Placeholders that will be replaced:
- {{USER_CODE}}: The generated test code from PlannerAgent
- {{SCENARIO_NAME}}: Name of the test scenario
- {{CONFIG}}: Test configuration dictionary
- {{HEADLESS}}: Browser headless mode (True/False)
"""

import json

# Import screenshot handler for consistent screenshot management
import os
import sys
import traceback
from datetime import datetime
from pathlib import Path

from playwright.sync_api import sync_playwright

sys.path.insert(0, os.path.join(os.getenv("ACTION_PATH", "."), "src"))
from utils.screenshot_handler import ScreenshotHandler

{{USER_CODE}}


def main():
    start_time = datetime.now()
    result = {
        "success": False,
        "message": "",
        "error": "",
        "execution_time": 0,
        "timestamp": start_time.isoformat(),
        "screenshot_path": None,
    }

    # Initialize screenshot handler
    screenshot_handler = ScreenshotHandler()
    scenario_name = {{SCENARIO_NAME}}

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless={{HEADLESS}})
            page = browser.new_page()

            # Set viewport
            page.set_viewport_size({"width": 1280, "height": 720})

            # Execute the test
            run_test(page, {{CONFIG}})

            # Capture success screenshot
            screenshot_path = screenshot_handler.capture_screenshot(
                page, screenshot_handler.SUCCESS, scenario_name
            )
            if screenshot_path:
                result["screenshot_path"] = screenshot_path

            browser.close()

        result["success"] = True
        result["message"] = "Test completed successfully"

    except Exception as e:
        result["error"] = str(e)
        result["traceback"] = traceback.format_exc()

        # Try to capture error screenshot
        if "page" in locals() and "browser" in locals():
            error_screenshot = screenshot_handler.capture_screenshot(
                page, screenshot_handler.ERROR, scenario_name
            )
            if error_screenshot:
                result["error_screenshot_path"] = error_screenshot

    finally:
        end_time = datetime.now()
        result["execution_time"] = (end_time - start_time).total_seconds()

    print(json.dumps(result, indent=2))
    return result["success"]


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
